services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html
    networks:
      - app_network
    environment:
      DATABASE_URL: sqlite:///var/www/html/database.sqlite3 

networks:
  app_network:
    driver: bridge